### ISSUE TITLE
Improper exception handling 

### ISSUE THREAD

**Issue by akondasif** [AdamBien/webcomponents-with-redux.training#2]
Greetings,

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of improper exception handling.

According to CWE, stack traces due to exception handling should not be printed. See https://cwe.mitre.org/ 

Source: https://github.com/AdamBien/webcomponents-with-redux.training/blob/master/validator/.mvn/wrapper/MavenWrapperDownloader.java

Fix: https://github.com/AdamBien/webcomponents-with-redux.training/pull/1 

I am interested to know if you agree with the findings. Any feedback is appreciated.

**Comment by AdamBien** [comment]
Thanks for the feedback -> MavenWrapperDownloader is a part of the Quarkus.io runtime which is out-of-scope in this project.
