### ISSUE TITLE
Redux course feedback

### ISSUE THREAD

**Issue by hrstoyanov** [AdamBien/webcomponents-with-redux.training#3]
@AdamBien thanks for the great course and effort!

I am half-way through it, enjoying it a lot, but wanted to give you some feedback:

1. You based the course on [Redux](https://redux.js.org/). However, raw redux might no longer be the recommended approach - [Redux Toolkit](https://redux-toolkit.js.org/) seems to be the recommended way to go in 2020. I accidentally learned about Redux Toolkit and why to prefer it over Redux from the [Redux is definitely not dead](https://changelog.com/jsparty/146)  podcast.

2. I think you create the JS files in a rigid boundary/control/entity fashion. However, it feels during the course that you end up with a lot of small files entangled with messy "import"s . I learned from the Redux recommendation documents that  [Ducks module pattern](https://github.com/erikras/ducks-modular-redux) is the [recommended](https://redux.js.org/style-guide/style-guide#structure-files-as-feature-folders-or-ducks) style for grouping reducer logic ... I wish you could follow it in the course.

3. For people new to Redux, it is worth spending some time explaining "why you need redux/redux toolkit" at all. For example, the custom events from your previous course are gone with redux .. and why this is a good thing.

4. Not very important, but I found it easier/cleaner to configure Snowpack as part of the NPM **package.json** itself. Notice the 

**snowpack/install**   and **snowpack/installOptions**  sections!

```
{
  "name": "dependencies",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@reduxjs/toolkit": "^1.4.0",
    "bulma": "^0.9.1",
    "lit-html": "^1.3.0",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "cypress": "^5.4.0",
    "snowpack": "^2.14.2"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "snowpack": {
    "install": [
      "lit-html",
      "redux",
      "@reduxjs/toolkit"
    ],
    "plugins": [],
    "installOptions": {
      "dest": "../events/src/lib",
      "treeshake": true
    },
    "devOptions": {
      "port": 4000,
      "open": "none"
    },
    "buildOptions": {
      "baseUrl": "../events/src",
      "webModulesUrl": "../events/src/lib"
    },
    "mount": {}
  }
}
```

**Comment by AdamBien** [comment]
Thanks for your feedback! I migrated the entire application to redux toolkit: https://vimeo.com/ondemand/redux and was able to simplify the codebase. I only used a subset or redux toolkit--it reflects the approach I'm using in "real world" projects.

I also extracted a quickstarter template after refactoring: https://adambien.blog/roller/abien/entry/web_components_bce_lit_html
